export const UFR_NOMS = {
    'SATIC':      "UFR SCIENCES APPLIQUEES ET TECHNOLOGIES DE L'INFORMATION ET DE LA COMMUNICATION (SATIC)",
    'UFR SATIC':  "UFR SCIENCES APPLIQUEES ET TECHNOLOGIES DE L'INFORMATION ET DE LA COMMUNICATION (SATIC)",

    'SDD':        "UFR SCIENCES DU DEVELOPPEMENT DURABLE (SDD)",
    'UFR SDD':    "UFR SCIENCES DU DEVELOPPEMENT DURABLE (SDD)",

    'ECOMIJ':     "UFR SCIENCES ECONOMIQUES, MANAGEMENT, INFORMATIQUE ET JURIDIQUES (ECOMIJ)",
    'UFR ECOMIJ': "UFR SCIENCES ECONOMIQUES, MANAGEMENT, INFORMATIQUE ET JURIDIQUES (ECOMIJ)",

    'ISFAR':      "INSTITUT SUPERIEUR DE FORMATION AGRICOLE ET RURALE (ISFAR)",
    'UFR ISFAR':  "INSTITUT SUPERIEUR DE FORMATION AGRICOLE ET RURALE (ISFAR)",
}

export function nomCompletUFR(code) {
    if (!code) return 'UFR'
    return UFR_NOMS[code] || UFR_NOMS[code.toUpperCase()] || code
}